apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: blog-infra
spec:
  ports:
    - port: 8848
      targetPort: 8848
      name: http
    - port: 9848
      targetPort: 9848
      name: grpc
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: blog-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      nodeSelector:
        node: node4
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.3.0
          ports:
            - containerPort: 8848
            - containerPort: 9848
          env:
            - name: MODE
              value: standalone
            - name: PREFER_HOST_MODE
              value: hostname
            - name: SPRING_DATASOURCE_PLATFORM
              value: ""
            - name: NACOS_AUTH_ENABLE
              value: "true"
            - name: NACOS_AUTH_TOKEN
              value: "SecretKey012345678901234567890123456789012345678901234567890123456789"
            - name: NACOS_AUTH_IDENTITY_KEY
              value: serverIdentity
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: security
            - name: JVM_XMS
              value: "256m"
            - name: JVM_XMX
              value: "256m"
          livenessProbe:
            httpGet:
              path: /nacos/v1/console/health/readiness
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
